export const jsFrameworks = [
  {
    name: "React",
    type: "Library",
    purpose: "Building user interfaces, especially SPAs",
    creator: "Facebook",
    releaseYear: 2013,
    website: "https://reactjs.org/",
    features: ["Component-based architecture", "Virtual DOM", "Hooks", "JSX"],
  },
  {
    name: "Vue",
    type: "Framework",
    purpose: "Building user interfaces and single-page applications",
    creator: "Evan You",
    releaseYear: 2014, 
    website: "https://vuejs.org/",
    features: ["Reactive data binding", "Component-based", "Virtual DOM", "Single-file components"],
  },
  {
    name: "Next.js",
    type: "Framework",
    purpose: "Server-side rendering, static site generation, and building full-stack applications",
    creator: "Vercel",
    releaseYear: 2016,
    website: "https://nextjs.org/",
    features: ["Hybrid rendering", "API Routes", "File-based routing", "Incremental Static Regeneration"],
  },
  {
    name: "Express",
    type: "Framework",
    purpose: "Building web servers and REST APIs",
    creator: "TJ Holowaychuk",
    releaseYear: 2010,
    website: "https://expressjs.com/",
    features: ["Middleware support", "Minimalistic", "Routing", "High-performance"],
  },
  {
    name: "Svelte",
    type: "Framework",
    purpose: "Building user interfaces with a compiler that produces highly optimized vanilla JavaScript",
    creator: "Rich Harris",
    releaseYear: 2016,
    website: "https://svelte.dev/",
    features: ["No virtual DOM", "Reactive assignments", "Compile-time optimizations", "Truly reactive state"],
  },
  {
    name: "Angular",
    type: "Framework",
    purpose: "Building large-scale web applications with MVC architecture",
    creator: "Google",
    releaseYear: 2010,
    website: "https://angular.io/",
    features: ["Two-way data binding", "Dependency injection", "TypeScript support", "Component-based architecture"],
  },
  {
    name: "NestJS",
    type: "Framework",
    purpose: "Building scalable and maintainable server-side applications",
    creator: "Kamil Myśliwiec",
    releaseYear: 2017,
    website: "https://nestjs.com/",
    features: ["Modular architecture", "Dependency injection", "TypeScript support", "Built-in testing tools"],
  },
  {
    name: "Nuxt",
    type: "Framework",
    purpose: "Server-side rendering and static site generation for Vue applications",
    creator: "Sébastien Chopin",
    releaseYear: 2016,
    website: "https://nuxtjs.org/",
    features: ["Server-side rendering", "Static site generation", "File-based routing", "Vue support"],
  },
  {
    name: "Gatsby",
    type: "Framework",
    purpose: "Building static sites with React",
    creator: "Kyle Mathews",
    releaseYear: 2015,
    website: "https://www.gatsbyjs.com/",
    features: ["Static site generation", "GraphQL data layer", "Plugins & Themes", "Image optimization"],
  },
  {
    name: "Ember",
    type: "Framework",
    purpose: "Building ambitious web applications",
    creator: "Yehuda Katz",
    releaseYear: 2011,
    website: "https://emberjs.com/",
    features: ["Convention over configuration", "Routing", "Components", "Handlebars templating"],
  }
]
